const list = [
    {
      id: 1,
      title: "React: Up & Running",
      author: "Stoyan Stefanov | 7 Dec 2021",
      price: 54.23,
      img: "https://m.media-amazon.com/images/I/418mC3XLQlL.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "JavaScript and jQuery",
      author: "Jon Duckett  | 21 Jul 2014",
      price: 61.38,
      img: "https://m.media-amazon.com/images/I/4119l82gW1L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Programming For Beginners",
      author: "Nathan Clark  | 21 May 2018",
      price: 23.99,
      img: "https://m.media-amazon.com/images/I/61-kW+Sg1WS._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "History of the Pelopennesian War",
      author: "Thucydides | 13 Sep 2017",
      price: 57,
      img: "https://images-na.ssl-images-amazon.com/images/I/51hsdFqRFuL._SX311_BO1,204,203,200_.jpg",
      amount: 1,
    },
    {
        id: 5,
        title: "The Histories",
        author: "Herodotus | 2 Jun 2009",
        price: 39.24,
        img: "https://m.media-amazon.com/images/I/A1OEaZgPKpL._AC_UL480_FMwebp_QL65_.jpg",
        amount: 1,
      },
    {
      id: 6,
      title: "The Persian Expedition",
      author: "Xenophon | 30 Jun 1950",
      price: 21.44,
      img: "https://m.media-amazon.com/images/I/81sF9RnNv2L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Rich Dad Poor Dad",
      author: "Robert T.Kiyosaki  | 11 Apr 2017",
      price: 23.66,
      img: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Masters of Command & the Genius of leadership",
      author: "Barry Strauss  | 6 Dec 2020",
      price: 18.99,
      img: "https://m.media-amazon.com/images/I/71DFP6vr+UL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Cognitive Behavioral Therapy",
      author: "Haldamir Taralom | 26 Dec 2019",
      price: 13.99,
      img: "https://m.media-amazon.com/images/I/81lxFurCsYL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Block Chain Investing",
      author: "Frank D. Futurist | 25 Aug 2021",
      price: 29.99,
      img: "https://m.media-amazon.com/images/I/818UQ6NtiyL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Principles For Dealing With The Changing World Order",
      author: "Ray Dalio  | 30 Nov 2021",
      price: 27.15,
      img: "https://m.media-amazon.com/images/I/61R4llNQbkL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "How To Invest In Gold & Silver",
      author: "Don Durrett | 1 Feb 2021",
      price: 27.67,
      img: "https://images-na.ssl-images-amazon.com/images/I/71hQBingjiL.jpg",
      amount: 1,
    },
  ];
  
  export default list;